# Generated by Django 5.2.14 on 2026-05-16 08:49

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Transporter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=200)),
                ('license_number', models.CharField(max_length=50, unique=True)),
                ('coverage_area', django.contrib.gis.db.models.fields.PolygonField(blank=True, null=True, srid=4326)),
                ('rating', models.FloatField(default=0.0)),
                ('total_deliveries', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='transporter_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'transporters',
            },
        ),
    ]
