# Generated by Django 5.2.14 on 2026-05-28 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transporters", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="transporter",
            old_name="is_active",
            new_name="is_available",
        ),
        migrations.AddField(
            model_name="transporter",
            name="city",
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name="transporter",
            name="current_active_orders",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="transporter",
            name="email",
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name="transporter",
            name="latitude",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="transporter",
            name="local_address",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="transporter",
            name="longitude",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="transporter",
            name="max_daily_orders",
            field=models.IntegerField(default=20),
        ),
        migrations.AddField(
            model_name="transporter",
            name="phone",
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name="transporter",
            name="responsable_name",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="transporter",
            name="service_radius_km",
            field=models.FloatField(default=20),
        ),
        migrations.AddField(
            model_name="transporter",
            name="status",
            field=models.CharField(
                choices=[
                    ("active", "Active"),
                    ("inactive", "Inactive"),
                    ("suspended", "Suspended"),
                ],
                default="active",
                max_length=20,
            ),
        ),
    ]
