# Generated by Django 5.2.14 on 2026-05-28 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vehicles", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="driver",
            name="status",
            field=models.CharField(
                choices=[
                    ("available", "Available"),
                    ("on_delivery", "On Delivery"),
                    ("offline", "Offline"),
                ],
                default="available",
                max_length=20,
            ),
        ),
    ]
